(Feature) Create small & simple  FV license server
GoodDollar/FaceTecSDK-custom-server pull request #1
Opened 2021-03-31 15:46 UTC by serdiukov-o-nordwhale

# Description

- [x] keep keys in the mongo
- [x] implement simple micro service to add new keys
- [x] zoom server should read own key at startup
- [x] send keys from zoom server via rest endpoint

About https://github.com/GoodDollar/GoodDAPP/issues/3175

# Checklist:
- [x] PR title matches follow: (Feature|Bug|Chore) Task Name
- [x] My code follows the style guidelines of this project
- [x] I have followed all the instructions described in the initial task (check Definitions of Done)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have added reference to a related issue in the repository
- [x] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [x] @mentions of the person or team responsible for reviewing proposed changes

2021-03-31 21:04 UTC, serdiukov-o-nordwhale commented on license/index.js
> + */
```suggestion
/**
 * Main loop
 */

 logger.info('Initializing mongoDB connection', { url: config.mongoUri, mongoOpts })

```

2021-04-01 16:06 UTC, omerzam requested changes

2021-04-01 16:06 UTC, omerzam commented on license/index.js
> +  const alreadyImported = await Model.exists({ expiryDate })
why not use findOneAndUpdate with upsert option to save a call to the DB and simplify the code?

2021-04-01 16:10 UTC, serdiukov-o-nordwhale commented on license/.env
> +MONGODB_URI=mongodb://localhost:27017,Alexs-MacBook-Pro-2.local:27017/gooddollar?replicaSet=local
1. i removed all secrets from here. 
2. this repo doesn't contain the applications ready to run. just our customizations. So we don't need to follow all the repo rules strictly

2021-04-01 16:11 UTC, serdiukov-o-nordwhale commented on license/.gitignore
> +node_modules/
se my answer above pls

2021-04-01 16:12 UTC, serdiukov-o-nordwhale commented on license/upload/.gitignore
> +*
could be replaced to .gitkeep

2021-04-01 16:12 UTC, serdiukov-o-nordwhale commented on license/index.js
> +    key = JSON.parse(key.replace(jsCommentRegexp, ''))
cool thanks.

2021-04-01 16:13 UTC, serdiukov-o-nordwhale commented on license/index.js
> +  const alreadyImported = await Model.exists({ expiryDate })
good idea tnx

2021-04-01 16:15 UTC, serdiukov-o-nordwhale commented on license/index.js
> +const [readFileAsync, unlinkAsync] = [readFile, unlink].map(promisify)
i think i'll use some wrapper package like this one https://www.npmjs.com/package/fs-async-promisify

2021-04-04 15:24 UTC, omerzam requested changes

2021-04-04 15:24 UTC, omerzam commented on license/Dockerfile
> +FROM node:10.21.0
this will produce a rather large docker image
did you consider trying alpine?

2021-04-04 15:24 UTC, omerzam commented on license/Dockerfile
> +COPY ["package.json", "package-lock.json*", ".env", "index.js", "./"]
consider seperating coping the package.json and package-lock.json and running npm install from coping the actualy code, this would make better use of docker cache mechanism.

https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

2021-04-04 15:24 UTC, omerzam commented on license/index.js
> +const stripJsonComments = require('strip-json-comments')
this seems to be an unpopular package and not sure how well maintained is it

2021-04-04 15:24 UTC, omerzam commented on license/index.js
> + const logger = (() => {
you seems to be doing a lot of heavy lifting just to have a proper logger, did you consider using a simpler logger like bunyan?

2021-04-05 11:41 UTC, serdiukov-o-nordwhale commented on FaceTecSDK-custom-server-9.0.16/src/main/java/com/facetec/customserver/classes/FaceTecServerState.java
> +            System.exit(0);
it's copy-pasted part of original source. 
In the additional checks i've added i decided to keep the original logic (e.g. exit with zero code)

2021-04-05 11:47 UTC, serdiukov-o-nordwhale commented on license/index.js
> + const logger = (() => {
i've used winston as it's used on goodserver and i have some experience with it and also some ready-to-use code parts  (e.g. formatter)

thanks for suggestion, i've look at bunyan when i would need to make another one micro sevice
for this one let's keep the current implementation - i see no reason to spend more time on learning bunyan, logger re-implementation, testing etc

2021-04-05 11:51 UTC, serdiukov-o-nordwhale commented on license/index.js
> +const stripJsonComments = require('strip-json-comments')
a) it's very simple and lightweight b) the other package you linked is keeping comments in the special Symbol-key fields while i just need to remove comments at all and parse JSON only

2021-04-06 11:38 UTC, omerzam commented on license/index.js
> +const { readFile, unlink } = require('fs-async-promisify')
this package is very unpopular and not very well maintained

2021-04-06 11:52 UTC, omerzam approved these changes

2021-04-07 07:06 UTC, sirpy requested changes

2021-04-07 07:06 UTC, sirpy commented on license/index.js
> +const winston = require('winston')
why do we also have a node js server?
from a simple task this has turned into a  23 files PR
from my POV after we first discussed it , it should be
1. facetec java server parses license file on start
2. facetec java server serves license on /license endpoint with type (web,native)
3. goodserver uses facetec /license endpoint

2021-04-07 10:27 UTC, serdiukov-o-nordwhale commented on license/index.js
> +const winston = require('winston')
there's no node server. script is just listening for uploads, parses file and adds it to the mongo
this allows us to update licenses without restarting server

Everything is as you listed

1. facetec loads license on start from DB
2. facetec provides /license endpoint with type
3. goodserver will use this endpoint
4. apps will call goodserver 

pt 3. 4. moved to the separete tasks

also 23 files are facetec server changes for pt 1-2 mostly
license parsing script contains everything inside index.js

2021-04-07 19:32 UTC, Zhigamovsky approved these changes

2021-04-07 20:04 UTC, merged